name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - id: do_test
        run: |
          echo hello > hello.txt
          false

      - id: foo
        run: |
          echo "::set-output name=exists::true"
        if: failure()

      - name: check steps.foo.outputs.exists
        run: echo ${{ steps.foo.outputs.exists }}
        if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: hello.txt
        if: steps.foo.outputs.exists
