name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - run: false

      - id: foo
        run: |
          echo "::set-output name=exists::true"
        if: failure()

      - run: echo ${{ steps.foo.outputs.exists }}
        if: always()
        continue-on-error: true

      - run: echo ${{ steps.foo.outputs.exists }} if steps.foo.outputs.exists
        if: steps.foo.outputs.exists
