name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - run: true

      - id: foo
        run: |
          echo "::set-output name=exists::true"
        if: always()

      - name: check steps.foo.outputs.exists
        run: echo ${{ steps.foo.outputs.exists }}
        if: always()

      - run: echo ${{ steps.foo.outputs.exists }} if steps.foo.outputs.exists
        if: steps.foo.outputs.exists
