name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - id: foo
        run: echo "::set-output name=bar::true"
      
      - run: echo ${{ steps.foo.outputs.bar }}

      - run: echo "bar is true"
        if: ${{ steps.foo.outputs.bar }}
