name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event) }}
      - id: do_test
        run: |
          echo hello > hello.txt
          false

      - id: foo
        run: |
          if [ -e 'hello.txt' ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          fi
        if: failure()

      - name: check steps.foo.outputs.exists
        run: echo ${{ steps.foo.outputs.exists }}
        if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: hello
          path: hello.txt
        if: failure() && steps.foo.outputs.exists == 'true'
