name: test
on:
  push:

jobs:
  test:
    name: annotate
    runs-on: ubuntu-latest
    steps:
      - id: foo
        run: |
          echo "::set-output name=exists::true"
      
      - run: echo ${{ steps.foo.outputs.exists }}
        if: always()

      - run: echo "exists is true"
        if: ${{ steps.foo.outputs.exists }}
